// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC5NK6Wzxf_HQZkhOBxpBxoyq9wtUNLhuU',
    appId: '1:332094720906:web:463c87745188fc3efb5673',
    messagingSenderId: '332094720906',
    projectId: 'vuvantrung-50605',
    authDomain: 'vuvantrung-50605.firebaseapp.com',
    databaseURL: 'https://vuvantrung-50605-default-rtdb.firebaseio.com',
    storageBucket: 'vuvantrung-50605.firebasestorage.app',
    measurementId: 'G-DXJYMQXT9C',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBwyDKzQINI0mCcv-nloknD9eL7BHrAOVs',
    appId: '1:332094720906:android:c686fd729e30625bfb5673',
    messagingSenderId: '332094720906',
    projectId: 'vuvantrung-50605',
    databaseURL: 'https://vuvantrung-50605-default-rtdb.firebaseio.com',
    storageBucket: 'vuvantrung-50605.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCFyyKMoWnUwVBQWTVQabt4-1AxOhHNkhw',
    appId: '1:332094720906:ios:0c1c4526dc197710fb5673',
    messagingSenderId: '332094720906',
    projectId: 'vuvantrung-50605',
    databaseURL: 'https://vuvantrung-50605-default-rtdb.firebaseio.com',
    storageBucket: 'vuvantrung-50605.firebasestorage.app',
    iosClientId: '332094720906-4ellm4sck3irqblt8feudhokalprob4s.apps.googleusercontent.com',
    iosBundleId: 'com.example.loginApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCFyyKMoWnUwVBQWTVQabt4-1AxOhHNkhw',
    appId: '1:332094720906:ios:0c1c4526dc197710fb5673',
    messagingSenderId: '332094720906',
    projectId: 'vuvantrung-50605',
    databaseURL: 'https://vuvantrung-50605-default-rtdb.firebaseio.com',
    storageBucket: 'vuvantrung-50605.firebasestorage.app',
    iosClientId: '332094720906-4ellm4sck3irqblt8feudhokalprob4s.apps.googleusercontent.com',
    iosBundleId: 'com.example.loginApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyC5NK6Wzxf_HQZkhOBxpBxoyq9wtUNLhuU',
    appId: '1:332094720906:web:a5ac8f6fe8875213fb5673',
    messagingSenderId: '332094720906',
    projectId: 'vuvantrung-50605',
    authDomain: 'vuvantrung-50605.firebaseapp.com',
    databaseURL: 'https://vuvantrung-50605-default-rtdb.firebaseio.com',
    storageBucket: 'vuvantrung-50605.firebasestorage.app',
    measurementId: 'G-HLTY5RZHRJ',
  );
}
